import React from "react";
import lottie from "lottie-web";
import Blob from "../assets/pinkblob.json";
import Dustbin from "../assets/dustbin.json";
import VBlob from "../assets/vblob.json";
import BBlob from "../assets/bblob.json";
import Svg from "../assets/man.png";
import { Logo, Nav, Button } from "../components";

const About = () => {
    React.useEffect(() => {
        lottie.loadAnimation({
            container: document.querySelector("#blob"), // the dom element that will contain the animation
            renderer: "svg",
            loop: true,
            autoplay: true,
            animationData: Blob, // the path to the animation json
        });
    }, []);
    React.useEffect(() => {
        lottie.loadAnimation({
            container: document.querySelector("#dust"), // the dom element that will contain the animation
            renderer: "svg",
            loop: true,
            autoplay: true,
            animationData: Dustbin, // the path to the animation json
        });
    }, []);
    React.useEffect(() => {
        lottie.loadAnimation({
            container: document.querySelector("#bblob"), // the dom element that will contain the animation
            renderer: "svg",
            loop: true,
            autoplay: true,
            animationData: BBlob, // the path to the animation json
        });
    }, []);
    React.useEffect(() => {
        lottie.loadAnimation({
            container: document.querySelector("#vblob"), // the dom element that will contain the animation
            renderer: "svg",
            loop: true,
            autoplay: true,
            animationData: VBlob, // the path to the animation json
        });
    }, []);

    return (
        <div className='relative'>
            <Logo />
            <Nav />
            <div class='parent w-full relative overflow-hidden'>
                <div class='div1 place-self-center'>
                    <div className='flex flex-col amed'>
                        <h1 className='text-5xl med'>Med</h1>
                        <p className='text-5xl med'>Bin</p>
                        <p className='text-xl  pt-4 leading-relaxed tracking wide'>
                            Healthcare waste management tech.
                        </p>
                        {/* <p className='text-xl leading-relaxed tracking wide'>
                            Lorem ipsum dolor sit amet adipisicing.
                        </p> */}
                        <Button />
                    </div>
                </div>
                <div class='div2 overflow-hidden m-auto '>
                    <div
                        id='blob'
                        className='-mt-5'
                        style={{ width: 800, height: 800 }}
                    ></div>
                </div>
                <img
                    src={Svg}
                    alt='man pixking garbage'
                    width='1500px'
                    className='absolute -top-[80px] left-[200px]'
                />
            </div>
            <div className='w-full mt-40 relative h-[90vh] overflow-hidden'>
                <h1 className='text-7xl amed text-center'>About the Project</h1>
                <div className='overflow-hidden absolute top-0 -right-[15%] -z-30'>
                    <div id='bblob' style={{ width: 400, height: 400 }}></div>
                </div>
                <p className='mx-auto w-3/5 areg text-xl text-center my-20 leading-relaxed tracking wider pb-30'>
                    Of the total amount of waste generated by health-care
                    activities, about 85% is general, non-hazardous waste. The
                    remaining 15% is considered hazardous material that may be
                    infectious, toxic or radioactive. Lakhs of rupees are spent
                    every year in the consequences of improper waste management.
                    <br />
                    <br />
                    <br />
                    To introduce measures to ensure the safe and environmentally
                    sound management of health care wastes, thereby preventing
                    adverse health and environmental impacts from such waste
                    including the unintended release of chemical or biological
                    hazards, including drug-resistant microorganisms, into the
                    environment thus protecting the health of patients, health
                    workers, and the general public.
                </p>
                <div className='overflow-hidden absolute -bottom-[15%] -left-[10%] -rotate-45'>
                    <div id='vblob' style={{ width: 400, height: 400 }}></div>
                </div>
            </div>
        </div>
    );
};

export default About;
