import React from "react";
import { Logo, Nav, Cursor } from "../components";
import Grp1 from "../assets/1.png";
import Grp2 from "../assets/2.png";
import Grp3 from "../assets/3.png";

const Idea = () => {
    return (
        <>
            <Logo />
            <Nav />
            <Cursor />
            <div className='p-8'>
                <div className='pb-8 max-h-screen text-center'>
                    <span className='text-6xl amed '>The Idea</span>
                </div>
                <div className='w-[60%] areg mx-auto text-xl text-center'>
                    Many of us must be aware of the current waste management!
                    This one is very highly prone to human error. This human
                    error costs us lives, and money. What if we could automate
                    this process? Have technology to make sure this waste
                    separation happens correctly!
                </div>
                <div className='p-8 py-16 relative'>
                    <p className='mt-[5rem] areg w-[60%] leading-relaxed tracking wider text-lg'>
                        Of the total amount of waste generated by health-care
                        activities, about 85% is general, non-hazardous waste.
                        The remaining 15% is considered hazardous material that
                        may be infectious, toxic or radioactive. Every year an
                        estimated 16 billion injections are administered
                        worldwide, but not all of the needles and syringes are
                        properly disposed of afterwards. Open burning and
                        incineration of health care wastes can, under some
                        circumstances, result in the emission of dioxins,
                        furans, and particulate matter. Lakhs of rupees are
                        spent every year in the consequences of improper waste
                        management
                    </p>
                    <div className='absolute top-[2rem] right-[4rem]'>
                        <img src={Grp1} width='400px' alt='blob' />
                    </div>
                </div>
                <div className='p-8 py-16 relative'>
                    <div className='absolute top-[5rem] left-[4rem]'>
                        <img src={Grp2} width='400px' alt='blob' />
                    </div>
                    <p className='mt-[5rem] areg w-[60%] leading-relaxed tracking wider text-lg ml-[38%]'>
                        Of the total amount of waste generated by health-care
                        activities, about 85% is general, non-hazardous waste.
                        The remaining 15% is considered hazardous material that
                        may be infectious, toxic or radioactive. Every year an
                        estimated 16 billion injections are administered
                        worldwide, but not all of the needles and syringes are
                        properly disposed of afterwards. Open burning and
                        incineration of health care wastes can, under some
                        circumstances, result in the emission of dioxins,
                        furans, and particulate matter. Lakhs of rupees are
                        spent every year in the consequences of improper waste
                        management
                    </p>
                </div>
                <div className='p-8 py-16 relative'>
                    <p className='mt-[5rem] areg w-[60%] leading-relaxed tracking wider text-lg'>
                        Of the total amount of waste generated by health-care
                        activities, about 85% is general, non-hazardous waste.
                        The remaining 15% is considered hazardous material that
                        may be infectious, toxic or radioactive. Every year an
                        estimated 16 billion injections are administered
                        worldwide, but not all of the needles and syringes are
                        properly disposed of afterwards. Open burning and
                        incineration of health care wastes can, under some
                        circumstances, result in the emission of dioxins,
                        furans, and particulate matter. Lakhs of rupees are
                        spent every year in the consequences of improper waste
                        management
                    </p>
                    <div className='absolute top-[2rem] right-[4rem]'>
                        <img src={Grp3} width='350px' alt='blob' />
                    </div>
                </div>
                <div className='p-8 py-16 relative'>
                    <div className='absolute top-[5rem] left-[4rem]'>
                        <img src={Grp1} width='400px' alt='blob' />
                    </div>
                    <p className='mt-[5rem] areg w-[60%] leading-relaxed tracking wider text-lg ml-[38%]'>
                        Of the total amount of waste generated by health-care
                        activities, about 85% is general, non-hazardous waste.
                        The remaining 15% is considered hazardous material that
                        may be infectious, toxic or radioactive. Every year an
                        estimated 16 billion injections are administered
                        worldwide, but not all of the needles and syringes are
                        properly disposed of afterwards. Open burning and
                        incineration of health care wastes can, under some
                        circumstances, result in the emission of dioxins,
                        furans, and particulate matter. Lakhs of rupees are
                        spent every year in the consequences of improper waste
                        management
                    </p>
                </div>
            </div>
        </>
    );
};

export default Idea;
